# Auto-generated by scripts/generate-contracts.mjs - DO NOT EDIT
from __future__ import annotations

from datetime import datetime
from typing import Any, Literal, Optional
from pydantic import BaseModel, Field

class CandidateEvent(BaseModel):
    address: str
    source: Literal["seed", "backfill", "daily"]
    ts: datetime
    tags: Optional[list[str]] = Field(default_factory=list)
    nickname: Optional[str] = None
    score_hint: Optional[float] = None
    meta: Optional[dict[str, Any]] = Field(default_factory=dict)
    notes: Optional[str] = None

class ScoreEvent(BaseModel):
    address: str
    score: float
    weight: float
    rank: int
    window_s: int
    ts: datetime
    meta: Optional[dict[str, Any]] = Field(default_factory=dict)

class FillEvent(BaseModel):
    fill_id: str
    source: Literal["fake", "hyperliquid"]
    address: str
    asset: str
    side: Literal["buy", "sell"]
    size: float
    price: float
    start_position: Optional[float] = None
    realized_pnl: Optional[float] = None
    ts: datetime
    meta: Optional[dict[str, Any]] = Field(default_factory=dict)

class OutcomeEvent(BaseModel):
    ticket_id: str
    closed_ts: datetime
    result_r: Optional[float] = None
    closed_reason: Literal["timebox", "manual", "error"]
    notes: Optional[str] = None

class SignalEvent(BaseModel):
    ticket_id: str
    address: str
    asset: str
    side: Literal["long", "short", "flat"]
    confidence: float
    score_ts: datetime
    signal_ts: datetime
    expires_at: datetime
    reason: Literal["consensus", "fallback"]
    payload: dict[str, Any] = Field(default_factory=dict)
