/* eslint-disable */
// Auto-generated by scripts/generate-contracts.mjs - DO NOT EDIT
import { z } from 'zod';

export const CandidateEventSchema = z.object({
  "address": z.string().regex(new RegExp("^0x[a-fA-F0-9]{40}$")),
  "source": z.enum(["seed", "backfill", "daily"]),
  "ts": z.string().datetime(),
  "tags": z.array(z.string().min(1).max(64)).optional().default([]),
  "nickname": z.union([z.string().min(1).max(64), z.null()]).optional(),
  "score_hint": z.union([z.number().min(-1).max(1), z.null()]).optional(),
  "meta": z.object({

}).catchall(z.any()).optional().default({}),
  "notes": z.union([z.string().max(280), z.null()]).optional()
}).strict();
export type CandidateEvent = z.infer<typeof CandidateEventSchema>;

export const ScoreEventSchema = z.object({
  "address": z.string().regex(new RegExp("^0x[a-fA-F0-9]{40}$")),
  "score": z.number().min(-1).max(1),
  "weight": z.number().min(0).max(1),
  "rank": z.number().int().min(1),
  "window_s": z.number().int().min(1),
  "ts": z.string().datetime(),
  "meta": z.object({

}).catchall(z.any()).optional().default({})
}).strict();
export type ScoreEvent = z.infer<typeof ScoreEventSchema>;

export const FillEventSchema = z.object({
  "fill_id": z.string().min(8).max(128),
  "source": z.enum(["fake", "hyperliquid"]),
  "address": z.string().regex(new RegExp("^0x[a-fA-F0-9]{40}$")),
  "asset": z.string().min(2).max(16),
  "side": z.enum(["buy", "sell"]),
  "size": z.number().gt(0),
  "price": z.number().gt(0),
  "start_position": z.union([z.number(), z.null()]).optional(),
  "realized_pnl": z.union([z.number(), z.null()]).optional(),
  "ts": z.string().datetime(),
  "meta": z.object({

}).catchall(z.any()).optional().default({})
}).strict();
export type FillEvent = z.infer<typeof FillEventSchema>;

export const OutcomeEventSchema = z.object({
  "ticket_id": z.string(),
  "closed_ts": z.string().datetime(),
  "result_r": z.union([z.number(), z.null()]).optional(),
  "closed_reason": z.enum(["timebox", "manual", "error"]),
  "notes": z.union([z.string().max(280), z.null()]).optional()
}).strict();
export type OutcomeEvent = z.infer<typeof OutcomeEventSchema>;

export const SignalEventSchema = z.object({
  "ticket_id": z.string(),
  "address": z.string().regex(new RegExp("^0x[a-fA-F0-9]{40}$")),
  "asset": z.string().min(2).max(16),
  "side": z.enum(["long", "short", "flat"]),
  "confidence": z.number().min(0).max(1),
  "score_ts": z.string().datetime(),
  "signal_ts": z.string().datetime(),
  "expires_at": z.string().datetime(),
  "reason": z.enum(["consensus", "fallback"]),
  "payload": z.object({

}).catchall(z.any()).default({})
}).strict();
export type SignalEvent = z.infer<typeof SignalEventSchema>;

export const MessageSchemas = {
  "a.candidates.v1": CandidateEventSchema,
  "b.scores.v1": ScoreEventSchema,
  "c.fills.v1": FillEventSchema,
  "d.outcomes.v1": OutcomeEventSchema,
  "d.signals.v1": SignalEventSchema
} as const;